/** Declaration file generated by dts-gen */

export = eslint_plugin_simple_import_sort;

declare const eslint_plugin_simple_import_sort: {
  meta: {
    name: string;
    version: string;
  };
  rules: {
    exports: {
      create: any;
      meta: {
        docs: {
          description: string;
          url: string;
        };
        fixable: string;
        messages: {
          sort: string;
        };
        schema: any[];
        type: string;
      };
    };
    imports: {
      create: any;
      meta: {
        docs: {
          description: string;
          url: string;
        };
        fixable: string;
        messages: {
          sort: string;
        };
        schema: {
          additionalProperties: boolean;
          properties: {
            groups: {
              items: {
                items: {
                  type: string;
                };
                type: string;
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
  };
};
