/** Declaration file generated by dts-gen */

export = eslint_plugin_better_tailwindcss;

declare const eslint_plugin_better_tailwindcss: {
  configs: {
    correctness: {
      plugins: string[];
      rules: {
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    "correctness-error": {
      plugins: string[];
      rules: {
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    "correctness-warn": {
      plugins: string[];
      rules: {
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    recommended: {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    "recommended-error": {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    "recommended-warn": {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-conflicting-classes": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
        "better-tailwindcss/no-unregistered-classes": string;
      };
    };
    stylistic: {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
      };
    };
    "stylistic-error": {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
      };
    };
    "stylistic-warn": {
      plugins: string[];
      rules: {
        "better-tailwindcss/enforce-consistent-class-order": string;
        "better-tailwindcss/enforce-consistent-line-wrapping": string;
        "better-tailwindcss/no-duplicate-classes": string;
        "better-tailwindcss/no-unnecessary-whitespace": string;
      };
    };
  };
  meta: {
    name: string;
  };
  rules: {
    "enforce-consistent-class-order": {
      create: any;
      meta: {
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            order: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "enforce-consistent-important-position": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            position: {
              description: string;
              enum: string[];
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "enforce-consistent-line-wrapping": {
      create: any;
      meta: {
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            classesPerLine: {
              default: number;
              description: string;
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            group: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            indent: {
              default: number;
              description: string;
              oneOf: {
                enum: string[];
                type: string;
              }[];
            };
            lineBreakStyle: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            preferSingleLine: {
              default: boolean;
              description: string;
              type: string;
            };
            printWidth: {
              default: number;
              description: string;
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "enforce-consistent-variable-syntax": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            syntax: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "enforce-shorthand-classes": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    multiline: {
      create: any;
      meta: {
        deprecated: {
          availableUntil: string;
          deprecatedSince: string;
          replacedBy: {
            message: string;
            rule: {
              name: string;
            };
          }[];
        };
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            classesPerLine: {
              default: number;
              description: string;
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            group: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            indent: {
              default: number;
              description: string;
              oneOf: {
                enum: string[];
                type: string;
              }[];
            };
            lineBreakStyle: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            preferSingleLine: {
              default: boolean;
              description: string;
              type: string;
            };
            printWidth: {
              default: number;
              description: string;
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-conflicting-classes": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-deprecated-classes": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-duplicate-classes": {
      create: any;
      meta: {
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-restricted-classes": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            restrict: {
              items: {
                anyOf: {
                  additionalProperties: boolean;
                  properties: {
                    fix: {
                      description: string;
                      type: string;
                    };
                    message: {
                      default: any;
                      description: string;
                      type: string;
                    };
                    pattern: {
                      description: string;
                      type: string;
                    };
                  };
                  required: string[];
                  type: string;
                }[];
              };
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-unnecessary-whitespace": {
      create: any;
      meta: {
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            allowMultiline: {
              default: boolean;
              description: string;
              type: string;
            };
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "no-unregistered-classes": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            detectComponentClasses: {
              default: boolean;
              description: string;
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            ignore: {
              description: string;
              items: {
                type: string;
              };
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "sort-classes": {
      create: any;
      meta: {
        deprecated: {
          availableUntil: string;
          deprecatedSince: string;
          replacedBy: {
            message: string;
            rule: {
              name: string;
            };
          }[];
        };
        docs: {
          category: string;
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        schema: {
          additionalProperties: boolean;
          properties: {
            attributes: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  type: string;
                }[];
              };
              type: string;
            };
            callees: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            entryPoint: {
              description: string;
              type: string;
            };
            order: {
              default: string;
              description: string;
              enum: string[];
              type: string;
            };
            tags: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
            tailwindConfig: {
              description: string;
              type: string;
            };
            tsconfig: {
              description: string;
              type: string;
            };
            variables: {
              description: string;
              items: {
                anyOf: {
                  description: string;
                  items: {
                    description: string;
                    type: string;
                  }[];
                  type: string;
                }[];
              };
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
  };
};
