/** Declaration file generated by dts-gen */

export = eslint_plugin_react_hooks;

declare const eslint_plugin_react_hooks: {
  configs: {
    flat: {
      recommended: {
        plugins: {
          "react-hooks": any;
        };
        rules: {
          "react-hooks/component-hook-factories": string;
          "react-hooks/config": string;
          "react-hooks/error-boundaries": string;
          "react-hooks/exhaustive-deps": string;
          "react-hooks/gating": string;
          "react-hooks/globals": string;
          "react-hooks/immutability": string;
          "react-hooks/incompatible-library": string;
          "react-hooks/preserve-manual-memoization": string;
          "react-hooks/purity": string;
          "react-hooks/refs": string;
          "react-hooks/rules-of-hooks": string;
          "react-hooks/set-state-in-effect": string;
          "react-hooks/set-state-in-render": string;
          "react-hooks/static-components": string;
          "react-hooks/unsupported-syntax": string;
          "react-hooks/use-memo": string;
        };
      };
      "recommended-latest": {
        plugins: {
          "react-hooks": any;
        };
        rules: {
          "react-hooks/component-hook-factories": string;
          "react-hooks/config": string;
          "react-hooks/error-boundaries": string;
          "react-hooks/exhaustive-deps": string;
          "react-hooks/gating": string;
          "react-hooks/globals": string;
          "react-hooks/immutability": string;
          "react-hooks/incompatible-library": string;
          "react-hooks/preserve-manual-memoization": string;
          "react-hooks/purity": string;
          "react-hooks/refs": string;
          "react-hooks/rules-of-hooks": string;
          "react-hooks/set-state-in-effect": string;
          "react-hooks/set-state-in-render": string;
          "react-hooks/static-components": string;
          "react-hooks/unsupported-syntax": string;
          "react-hooks/use-memo": string;
          "react-hooks/void-use-memo": string;
        };
      };
    };
    recommended: {
      plugins: string[];
      rules: {
        "react-hooks/component-hook-factories": string;
        "react-hooks/config": string;
        "react-hooks/error-boundaries": string;
        "react-hooks/exhaustive-deps": string;
        "react-hooks/gating": string;
        "react-hooks/globals": string;
        "react-hooks/immutability": string;
        "react-hooks/incompatible-library": string;
        "react-hooks/preserve-manual-memoization": string;
        "react-hooks/purity": string;
        "react-hooks/refs": string;
        "react-hooks/rules-of-hooks": string;
        "react-hooks/set-state-in-effect": string;
        "react-hooks/set-state-in-render": string;
        "react-hooks/static-components": string;
        "react-hooks/unsupported-syntax": string;
        "react-hooks/use-memo": string;
      };
    };
    "recommended-latest": {
      plugins: string[];
      rules: {
        "react-hooks/component-hook-factories": string;
        "react-hooks/config": string;
        "react-hooks/error-boundaries": string;
        "react-hooks/exhaustive-deps": string;
        "react-hooks/gating": string;
        "react-hooks/globals": string;
        "react-hooks/immutability": string;
        "react-hooks/incompatible-library": string;
        "react-hooks/preserve-manual-memoization": string;
        "react-hooks/purity": string;
        "react-hooks/refs": string;
        "react-hooks/rules-of-hooks": string;
        "react-hooks/set-state-in-effect": string;
        "react-hooks/set-state-in-render": string;
        "react-hooks/static-components": string;
        "react-hooks/unsupported-syntax": string;
        "react-hooks/use-memo": string;
        "react-hooks/void-use-memo": string;
      };
    };
  };
  meta: {
    name: string;
    version: string;
  };
  rules: {
    "automatic-effect-dependencies": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "capitalized-calls": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "component-hook-factories": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    config: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "error-boundaries": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "exhaustive-deps": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          enableDangerousAutofixThisMayCauseInfiniteLoops: boolean;
          properties: {
            additionalHooks: {
              type: string;
            };
            enableDangerousAutofixThisMayCauseInfiniteLoops: {
              type: string;
            };
            experimental_autoDependenciesHooks: {
              items: {
                type: string;
              };
              type: string;
            };
            requireExplicitEffectDeps: {
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    fbt: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    fire: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    gating: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    globals: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    hooks: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    immutability: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "incompatible-library": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    invariant: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "memoized-effect-dependencies": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "no-deriving-state-in-effects": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "preserve-manual-memoization": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    purity: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    refs: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "rule-suppression": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "rules-of-hooks": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
          url: string;
        };
        schema: {
          additionalProperties: boolean;
          properties: {
            additionalHooks: {
              type: string;
            };
          };
          type: string;
        }[];
        type: string;
      };
    };
    "set-state-in-effect": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "set-state-in-render": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "static-components": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    syntax: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    todo: {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "unsupported-syntax": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "use-memo": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
    "void-use-memo": {
      create: any;
      meta: {
        docs: {
          description: string;
          recommended: boolean;
        };
        fixable: string;
        hasSuggestions: boolean;
        schema: {
          additionalProperties: boolean;
          type: string;
        }[];
        type: string;
      };
    };
  };
};
