/** Declaration file generated by dts-gen */

export = prettier_plugin_organize_imports;

declare const prettier_plugin_organize_imports: {
  options: {
    organizeImportsSkipDestructiveCodeActions: {
      category: string;
      default: boolean;
      description: string;
      type: string;
    };
    organizeImportsTypeOrder: {
      category: string;
      choices: {
        description: string;
        value: string;
      }[];
      description: string;
      type: string;
    };
  };
  parsers: {
    babel: {
      astFormat: string;
      hasIgnorePragma: any;
      hasPragma: any;
      locEnd: any;
      locStart: any;
      parse: any;
      preprocess: any;
    };
    "babel-ts": {
      astFormat: string;
      hasIgnorePragma: any;
      hasPragma: any;
      locEnd: any;
      locStart: any;
      parse: any;
      preprocess: any;
    };
    typescript: {
      astFormat: string;
      hasIgnorePragma: any;
      hasPragma: any;
      locEnd: any;
      locStart: any;
      parse: any;
      preprocess: any;
    };
    vue: {
      astFormat: string;
      hasIgnorePragma: any;
      hasPragma: any;
      locEnd: any;
      locStart: any;
      parse: any;
      preprocess: any;
    };
  };
};
